// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ICIvVnz390Kb9XFuT1WoRiK5CCcE6io',
    appId: '1:647768681890:android:96ecfb50c28c0614b956fb',
    messagingSenderId: '647768681890',
    projectId: 'shopsphere-64b5f',
    storageBucket: 'shopsphere-64b5f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA50e5aHuqbwLgsLSOTNoukK_g7fk5KTzQ',
    appId: '1:647768681890:ios:79a2af9eab2a366cb956fb',
    messagingSenderId: '647768681890',
    projectId: 'shopsphere-64b5f',
    storageBucket: 'shopsphere-64b5f.firebasestorage.app',
    androidClientId: '647768681890-0jcrs51f1mvnpthruqbobi5gf8k5uda7.apps.googleusercontent.com',
    iosClientId: '647768681890-csv9q1v53mjlhejbkp0n1h478imnvp5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsphere',
  );
}
